# https://docs.travis-ci.com/user/languages/java/
language: java

jdk:
  - openjdk10

notifications:
  email:
    recipients:
      - silver19987@gmail.com
      - yura12777@gmail.com
      - b__vica@mail.ru

after_success:
  - bash <(curl -s https://codecov.io/bash)