/* Generated By:JavaCC: Do not edit this line. SqlParser.java */
    package com.dbms.grammar;

    import java.util.ArrayList;
    import java.util.LinkedHashMap;
    import java.util.Map;

    import com.dbms.backend.*;

    public class SqlParser implements SqlParserConstants {
        void run() throws Exception {
            while (true) {
                try {
                    parse();
                } catch(Throwable e) {
                    e.printStackTrace();
                }
            }
        }

  final public void parse() throws ParseException, Exception {
    if (jj_2_1(2)) {
      parseShowCreateTable();
    } else if (jj_2_2(2)) {
      parseCreateTable();
    } else if (jj_2_3(2)) {
      parseExit();
    } else if (jj_2_4(2)) {
      parseCreateDatabase();
    } else if (jj_2_5(2)) {
      parseUseDatabase();
    } else if (jj_2_6(2)) {
      jj_consume_token(0);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void parseUseDatabase() throws ParseException, Exception {
    Token name, command;
    command = jj_consume_token(USE);
    jj_consume_token(DATABASE);
    name = jj_consume_token(STRING_LITERAL);
    jj_consume_token(SEMICOLON);
        DataBases.useDataBase(name.image);
    if (jj_2_7(2)) {
      parse();
    } else {
      ;
    }
  }

  final public void parseCreateDatabase() throws ParseException, Exception {
    Token name, command;
    command = jj_consume_token(CREATE);
    jj_consume_token(DATABASE);
    name = jj_consume_token(STRING_LITERAL);
    jj_consume_token(SEMICOLON);
        DataBases.createDataBase(name.image);
    if (jj_2_8(2)) {
      parse();
    } else {
      ;
    }
  }

/*
void parseDropDatabase():
{
    Token name, command;
}
{
    command = <DROP><DATABASE>
    name = <STRING_LITERAL>
    <SEMICOLON>
    [parse()]
}

void parseDropTable():
{
    Token name, command;
}
{
    command = <DROP><TABLE>
    name = <STRING_LITERAL>
    <SEMICOLON>
    [parse()]
}
*/
  final public void parseShowCreateTable() throws ParseException, Exception {
    Token name, command;
    command = jj_consume_token(SHOW);
    jj_consume_token(CREATE);
    jj_consume_token(TABLE);
    name = jj_consume_token(STRING_LITERAL);
    jj_consume_token(SEMICOLON);
        System.out.println(
            DataBases.getCurrentDataBase().showCreate(name.image)
        );
    if (jj_2_9(2)) {
      parse();
    } else {
      ;
    }
  }

  final public void parseCreateTable() throws ParseException, Exception {
    Token name, command;
    command = jj_consume_token(CREATE);
    jj_consume_token(TABLE);
    name = jj_consume_token(STRING_LITERAL);
    jj_consume_token(OPEN_BRACKET);
        DataBases.getCurrentDataBase().createTable(
            new Table(
                new TableHeader(
                    name.image,
                    getFields()
                )
            )
        );
    jj_consume_token(CLOSE_BRACKET);
    jj_consume_token(SEMICOLON);
    if (jj_2_10(2)) {
      parse();
    } else {
      ;
    }
  }

  final public Token parseExit() throws ParseException {
    Token command;
    command = jj_consume_token(EXIT);
    jj_consume_token(SEMICOLON);
        DataBases.exit();
        {if (true) return command;}
    throw new Error("Missing return statement in function");
  }

  final public ArgsGuard parseSelectFromTable() throws ParseException, Exception {
    Token name, command, limit = null, offset = null;

    ArrayList<String> columns = new ArrayList<String>();

    ArgsGuard args = new ArgsGuard();
    command = jj_consume_token(SELECT);
    columns = getColumns();
    jj_consume_token(FROM);
    name = jj_consume_token(STRING_LITERAL);
    if (jj_2_11(2)) {
      jj_consume_token(LIMIT);
      limit = jj_consume_token(STRING_LITERAL);
    } else {
      ;
    }
    if (jj_2_12(2)) {
      jj_consume_token(OFFSET);
      offset = jj_consume_token(STRING_LITERAL);
    } else {
      ;
    }
    jj_consume_token(SEMICOLON);
        args.setName(name.image);
        args.setColumns(columns);

        if (limit != null)
            args.setLimit(Integer.parseInt(limit.image));

        if (offset != null)
            args.setOffset(Integer.parseInt(offset.image));

        {if (true) return args;}
    throw new Error("Missing return statement in function");
  }

  final public ArgsGuard parseInsertIntoTable() throws ParseException, Exception {
    Token name, command;

    ArrayList<String> columns = new ArrayList<String>();
    ArrayList<String> insertableValues = new ArrayList<String>();

    ArgsGuard args = new ArgsGuard();
    command = jj_consume_token(INSERT);
    if (jj_2_13(2)) {
      jj_consume_token(INTO);
    } else {
      ;
    }
    name = jj_consume_token(STRING_LITERAL);
    jj_consume_token(OPEN_BRACKET);
    columns = getColumns();
    jj_consume_token(CLOSE_BRACKET);
    jj_consume_token(VALUES);
    jj_consume_token(OPEN_BRACKET);
    insertableValues = getInsertableValues();
    jj_consume_token(CLOSE_BRACKET);
    jj_consume_token(SEMICOLON);
        args.setName(name.image);
        args.setColumns(columns);
        args.setInsertableValues(insertableValues);

        {if (true) return args;}
    throw new Error("Missing return statement in function");
  }

/*ArgsGuard parseUpdate() throws Exception:
{
    Token name;

    ArgsGuard args = new ArgsGuard();
}
{
    <UPDATE>
    <SEMICOLON>
    {
        args.setName(name.image);

        return args;
    }
    //FIXME: this command need run
    //[parse()]
}*/
  final public ArgsGuard parseDelete() throws ParseException, Exception {
    Token name, compareColumn = null, compareSign = null, compareValue = null, comparePredicat = null;

    ArrayList<String> compareColumns = new ArrayList<String>();
    ArrayList<String> compareSigns = new ArrayList<String>();
    ArrayList<String> compareValues = new ArrayList<String>();
    ArrayList<String> comparePredicats = new ArrayList<String>();

    ArgsGuard args = new ArgsGuard();
    jj_consume_token(DELETE);
    jj_consume_token(FROM);
    name = jj_consume_token(STRING_LITERAL);
    if (jj_2_15(2)) {
      jj_consume_token(WHERE);
      compareColumn = jj_consume_token(STRING_LITERAL);
      compareSign = jj_consume_token(COMPARE);
      compareValue = jj_consume_token(STRING_LITERAL);
            compareColumns.add(compareColumn.image);
            compareSigns.add(compareSign.image);
            compareValues.add(compareValue.image);
      label_1:
      while (true) {
        if (jj_2_14(2)) {
          ;
        } else {
          break label_1;
        }
        comparePredicat = jj_consume_token(PREDICAT);
        compareColumn = jj_consume_token(STRING_LITERAL);
        compareSign = jj_consume_token(COMPARE);
        compareValue = jj_consume_token(STRING_LITERAL);
                compareColumns.add(compareColumn.image);
                compareSigns.add(compareSign.image);
                compareValues.add(compareValue.image);
                comparePredicats.add(comparePredicat.image);
      }
    } else {
      ;
    }
    jj_consume_token(SEMICOLON);
        args.setName(name.image);
        args.setCompareColumns(compareColumns);
        args.setCompareSigns(compareSigns);
        args.setCompareValues(compareValues);
        args.setComparePredicats(comparePredicats);

        {if (true) return args;}
    throw new Error("Missing return statement in function");
  }

  final public ArrayList<String> getColumns() throws ParseException {
    Token columnName;

    ArrayList<String> columns = new ArrayList<String>();
    columnName = jj_consume_token(STRING_LITERAL);
     columns.add(columnName.image);
    label_2:
    while (true) {
      if (jj_2_16(2)) {
        ;
      } else {
        break label_2;
      }
      jj_consume_token(COMMA);
      columnName = jj_consume_token(STRING_LITERAL);
            columns.add(columnName.image);
    }
     {if (true) return columns;}
    throw new Error("Missing return statement in function");
  }

  final public ArrayList<String> getInsertableValues() throws ParseException {
    Token value;

    ArrayList<String> values = new ArrayList<String>();
    jj_consume_token(SINGLE_MARK);
    value = jj_consume_token(STRING_LITERAL);
    jj_consume_token(SINGLE_MARK);
     values.add(value.image);
    label_3:
    while (true) {
      if (jj_2_17(2)) {
        ;
      } else {
        break label_3;
      }
      jj_consume_token(COMMA);
      jj_consume_token(SINGLE_MARK);
      value = jj_consume_token(STRING_LITERAL);
      jj_consume_token(SINGLE_MARK);
            values.add(value.image);
    }
     {if (true) return values;}
    throw new Error("Missing return statement in function");
  }

  final public Map<String, TypeDescription> getFields() throws ParseException {
    Token name;

    Map<String, TypeDescription> fields = new LinkedHashMap<String, TypeDescription>();
    name = jj_consume_token(STRING_LITERAL);
        fields.put(name.image, getTypeDescription());
    if (jj_2_18(2)) {
      jj_consume_token(COMMA);
      getFields();
    } else {
      ;
    }
     {if (true) return fields;}
    throw new Error("Missing return statement in function");
  }

  final public TypeDescription getTypeDescription() throws ParseException {
    Token type, length = null;

    TypeDescription typeDescription;
    type = jj_consume_token(STRING_LITERAL);
    if (jj_2_19(2)) {
      jj_consume_token(OPEN_BRACKET);
      length = jj_consume_token(STRING_LITERAL);
      jj_consume_token(CLOSE_BRACKET);
    } else {
      ;
    }
        typeDescription = new TypeDescription(type.image);

        if (length != null)
            typeDescription.setLength(length.image);

        {if (true) return typeDescription;}
    throw new Error("Missing return statement in function");
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_5(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_6(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_7(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_8(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_2_9(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_9(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  private boolean jj_2_10(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_10(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  private boolean jj_2_11(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_11(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  private boolean jj_2_12(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_12(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  private boolean jj_2_13(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_13(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  private boolean jj_2_14(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_14(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  private boolean jj_2_15(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_15(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  private boolean jj_2_16(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_16(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  private boolean jj_2_17(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_17(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  private boolean jj_2_18(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_18(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  private boolean jj_2_19(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_19(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  private boolean jj_3R_7() {
    if (jj_scan_token(CREATE)) return true;
    if (jj_scan_token(DATABASE)) return true;
    return false;
  }

  private boolean jj_3_9() {
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3_18() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_10()) return true;
    return false;
  }

  private boolean jj_3R_10() {
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3_7() {
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3R_4() {
    if (jj_scan_token(SHOW)) return true;
    if (jj_scan_token(CREATE)) return true;
    return false;
  }

  private boolean jj_3R_6() {
    if (jj_scan_token(EXIT)) return true;
    if (jj_scan_token(SEMICOLON)) return true;
    return false;
  }

  private boolean jj_3R_8() {
    if (jj_scan_token(USE)) return true;
    if (jj_scan_token(DATABASE)) return true;
    return false;
  }

  private boolean jj_3_17() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_scan_token(SINGLE_MARK)) return true;
    return false;
  }

  private boolean jj_3_10() {
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3_6() {
    if (jj_scan_token(0)) return true;
    return false;
  }

  private boolean jj_3_19() {
    if (jj_scan_token(OPEN_BRACKET)) return true;
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3_14() {
    if (jj_scan_token(PREDICAT)) return true;
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3_5() {
    if (jj_3R_8()) return true;
    return false;
  }

  private boolean jj_3_4() {
    if (jj_3R_7()) return true;
    return false;
  }

  private boolean jj_3_3() {
    if (jj_3R_6()) return true;
    return false;
  }

  private boolean jj_3_12() {
    if (jj_scan_token(OFFSET)) return true;
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3_2() {
    if (jj_3R_5()) return true;
    return false;
  }

  private boolean jj_3_11() {
    if (jj_scan_token(LIMIT)) return true;
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3_13() {
    if (jj_scan_token(INTO)) return true;
    return false;
  }

  private boolean jj_3_16() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_9() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_1()) {
    jj_scanpos = xsp;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3_4()) {
    jj_scanpos = xsp;
    if (jj_3_5()) {
    jj_scanpos = xsp;
    if (jj_3_6()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_4()) return true;
    return false;
  }

  private boolean jj_3_8() {
    if (jj_3R_9()) return true;
    return false;
  }

  private boolean jj_3R_5() {
    if (jj_scan_token(CREATE)) return true;
    if (jj_scan_token(TABLE)) return true;
    return false;
  }

  private boolean jj_3_15() {
    if (jj_scan_token(WHERE)) return true;
    if (jj_scan_token(STRING_LITERAL)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public SqlParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[19];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public SqlParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public SqlParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new SqlParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public SqlParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new SqlParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public SqlParser(SqlParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(SqlParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 0; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[35];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 0; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 35; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 19; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
            case 4: jj_3_5(); break;
            case 5: jj_3_6(); break;
            case 6: jj_3_7(); break;
            case 7: jj_3_8(); break;
            case 8: jj_3_9(); break;
            case 9: jj_3_10(); break;
            case 10: jj_3_11(); break;
            case 11: jj_3_12(); break;
            case 12: jj_3_13(); break;
            case 13: jj_3_14(); break;
            case 14: jj_3_15(); break;
            case 15: jj_3_16(); break;
            case 16: jj_3_17(); break;
            case 17: jj_3_18(); break;
            case 18: jj_3_19(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

    }
