/* Generated By:JavaCC: Do not edit this line. SqlParserConstants.java */
package com.dbms.grammar;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int CREATE = 9;
  /** RegularExpression Id. */
  int DATABASE = 10;
  /** RegularExpression Id. */
  int DELETE = 11;
  /** RegularExpression Id. */
  int DROP = 12;
  /** RegularExpression Id. */
  int EXIT = 13;
  /** RegularExpression Id. */
  int FROM = 14;
  /** RegularExpression Id. */
  int INSERT = 15;
  /** RegularExpression Id. */
  int INTO = 16;
  /** RegularExpression Id. */
  int LIMIT = 17;
  /** RegularExpression Id. */
  int OFFSET = 18;
  /** RegularExpression Id. */
  int SELECT = 19;
  /** RegularExpression Id. */
  int SHOW = 20;
  /** RegularExpression Id. */
  int TABLE = 21;
  /** RegularExpression Id. */
  int UPDATE = 22;
  /** RegularExpression Id. */
  int USE = 23;
  /** RegularExpression Id. */
  int VALUES = 24;
  /** RegularExpression Id. */
  int WHERE = 25;
  /** RegularExpression Id. */
  int PREDICAT = 26;
  /** RegularExpression Id. */
  int INVERSE = 27;
  /** RegularExpression Id. */
  int COMPARE = 28;
  /** RegularExpression Id. */
  int STRING_LITERAL = 29;
  /** RegularExpression Id. */
  int STAR = 30;
  /** RegularExpression Id. */
  int SEMICOLON = 31;
  /** RegularExpression Id. */
  int SINGLE_MARK = 32;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 33;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 34;
  /** RegularExpression Id. */
  int COMMA = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\\\\"",
    "\"\\t\"",
    "\" \"",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"CREATE\"",
    "\"DATABASE\"",
    "\"DELETE\"",
    "\"DROP\"",
    "\"EXIT\"",
    "\"FROM\"",
    "\"INSERT\"",
    "\"INTO\"",
    "\"LIMIT\"",
    "\"OFFSET\"",
    "\"SELECT\"",
    "\"SHOW\"",
    "\"TABLE\"",
    "\"UPDATE\"",
    "\"USE\"",
    "\"VALUES\"",
    "\"WHERE\"",
    "<PREDICAT>",
    "\"NOT\"",
    "<COMPARE>",
    "<STRING_LITERAL>",
    "\"*\"",
    "\";\"",
    "\"\\\'\"",
    "\"(\"",
    "\")\"",
    "\",\"",
  };

}
